export const seafarerData = [
 
    {
      sno: "1",
      name: "K R Ashwath",
      idNumber: "18051988",
      IdType: "Passport",
      location: "India",
      email: "ash@gmail.com",
      phone: "9791917536",
      ship: "Ms Training Ship1",
      ship1: "(oilTanker)",
      role: "Deck Rating",
      status: "Active",
    },
    {
      sno: "2",
      name: "Michaell",
      idNumber: "18051988",
      IdType: "Passport",
      location: "India",
      email: "mick@gmail.com",
      phone: "9775647536",
      ship: "Ms Training Ship1",
      ship1: "(oilTanker)",
      role: "Deck Rating",
      status: "Active",
    },
    {
      sno: "3",
      name: "Hari Prasath",
      idNumber: "18051988",
      IdType: "Passport",
      location: "India",
      email: "ramacha@gmail.com",
      phone: "9791917536",
      ship: "Ms Training Ship1",
      ship1: "(oilTanker)",
      role: "Deck Rating",
      status: "Active",
    },
    {
      sno: "4",
      name: "Anbarasan",
      idNumber: "18051988",
      IdType: "Passport",
      location: "India",
      email: "ramacha@gmail.com",
      phone: "9791917536",
      ship: "Ms Training Ship1",
      ship1: "(oilTanker)",
      role: "Deck Rating",
      status: "Active",
    },
    {
      sno: "5",
      name: "Ramachandran Anath",
      idNumber: "18051988",
      IdType: "Passport",
      location: "India",
      email: "ramacha@gmail.com",
      phone: "9791917536",
      ship: "Ms Training Ship1",
      ship1: "(oilTanker)",
      role: "Deck Rating",
      status: "Active",
    },
    {
      sno: "6",
      name: "Mugilan",
      idNumber: "18051988",
      IdType: "Passport",
      location: "India",
      email: "ramacha@gmail.com",
      phone: "9791917536",
      ship: "Ms Training Ship1",
      ship1: "(oilTanker)",
      role: "Deck Rating",
      status: "Active",
    },
    {
      sno: "7",
      name: "Rammoorthi",
      idNumber: "18051988",
      IdType: "Passport",
      location: "India",
      email: "ramacha@gmail.com",
      phone: "9791917536",
      ship: "Ms Training Ship1",
      ship1: "(oilTanker)",
      role: "Deck Rating",
      status: "Active",
    },
    {
      sno: "8",
      name: "Prasanth",
      idNumber: "18051988",
      IdType: "Passport",
      location: "India",
      email: "mick@gmail.com",
      phone: "9775647536",
      ship: "Ms Training Ship1",
      ship1: "(oilTanker)",
      role: "Deck Rating",
      status: "Active",
    },
    {
      sno: "9",
      name: "Dhanaraj",
      idNumber: "18051988",
      IdType: "Passport",
      location: "India",
      email: "mick@gmail.com",
      phone: "9775647536",
      ship: "Ms Training Ship1",
      ship1: "(oilTanker)",
      role: "Deck Rating",
      status: "Active",
    },
    {
      sno: "10",
      name: "Michael",
      idNumber: "18051988",
      IdType: "Passport",
      location: "India",
      email: "mick@gmail.com",
      phone: "9775647536",
      ship: "Ms Training Ship1",
      ship1: "(oilTanker)",
      role: "Deck Rating",
      status: "Active",
    },
    {
      sno: "11",
      name: "Michael",
      idNumber: "18051988",
      IdType: "Passport",
      location: "India",
      email: "mick@gmail.com",
      phone: "9775647536",
      ship: "Ms Training Ship1",
      ship1: "(oilTanker)",
      role: "Deck Rating",
      status: "Active",
    },
    {
      sno: "12",
      name: "Michael",
      idNumber: "18051988",
      IdType: "Passport",
      location: "India",
      email: "mick@gmail.com",
      phone: "9775647536",
      ship: "Ms Training Ship1",
      ship1: "(oilTanker)",
      role: "Deck Rating",
      status: "Active",
    },
    {
      sno: "13",
      name: "Michael",
      idNumber: "18051988",
      IdType: "Passport",
      location: "India",
      email: "mick@gmail.com",
      phone: "9775647536",
      ship: "Ms Training Ship1",
      ship1: "(oilTanker)",
      role: "Deck Rating",
      status: "Active",
    },
    {
      sno: "14",
      name: "Michael",
      idNumber: "18051988",
      IdType: "Passport",
      location: "India",
      email: "mick@gmail.com",
      phone: "9775647536",
      ship: "Ms Training Ship1",
      ship1: "(oilTanker)",
      role: "Deck Rating",
      status: "Active",
    },
  ]

